name: CI tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.8.10
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7
      - run: poetry install
      - run: poetry run mypy .
      - run: poetry run pytest
